version: '3.3'
services:
  tracks-backend:
    image: stefanroeck/tracks-backend
    container_name: tracks-backend
    restart: unless-stopped
    logging:
      options:
        max-size: 1g
    env_file: [ ./config/application.properties ]
    build:
      dockerfile: ./scripts/docker/Dockerfile
    ports:
      - '8082:8082'
    volumes:
      - h2-data:/data/db
volumes:
  h2-data:
    driver: local